.TH man 7 "27 Dec 2017" "1.0" "disas man page"
.SH NAME
disas \- disassembles Corewar files into ASM files
.SH SYNOPSIS
disas [-v] <file> ...
.SH DESCRIPTION
The disas program takes Corewar files as parameters and disassembles them into ASM files.
.SH OPTIONS
.IP "-v"
launches in visualization mode.
.SH VISUALIZATION MODE
tapui sur les fleche sa fe des truc
pis entree ca fe autr choz
.SH BUGS
None known.
.SH AUTHOR
jafagpo